language: node_js

node_js: 
  - 10.3.0

jobs: 
  include:
    - stage: test
      script: 
        - yarn test
    - stage: fossa
      script:
        - curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
        - fossa

